{
    "swagger": "2.0",
    "info": {
        "version": "1.0.0",
        "title": "REST API Balneario Atonaltzin",
        "description": "<html><body>Documentacion del servidor para el proyecto <b>Balneario Atonaltzin</b></body></html>",
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        }
    },
    "host": "localhost:3000",
    "basePath": "",
    "tags": [
        {
            "name": "Cabañas",
            "description": "API para obtener información de las cabanas atonaltzin"
        },
        {
            "name": "Reservaciones",
            "description": "API para obtener información de las reservaciones de atonaltzin"
        },
        {
            "name": "Cobros",
            "description": "API para obtener información de los cobros de reservaciones"
        },
        {
            "name": "Usuarios",
            "description": "API para obtener información de los usuarios"
        }
    ],
    "schemes": [
        "http"
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/api/cabanas/crearcabana": {
            "post": {
                "summary": "Agregar una cabaña",
                "operationId": "create",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "Cabañas",
                        "in": "body",
                        "description": "Cabaña agregada",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/NuevaCabana"
                        }
                    }
                ],
                "tags": [
                    "Cabañas"
                ],
                "responses": {
                    "200": {
                        "description": "Insertado con exito"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/cabanas/MostrarTodasCabanas": {
            "get": {
                "tags": [
                    "Cabañas"
                ],
                "summary": "Listado de todas las cabañas que existen",
                "description": "<p>Servicio que devuelve la información detallada de todas las cabañas que existen en el balneario atonaltzin.</p><p>&nbsp;</p><p><em><strong>¿Cuáles son las cabanas registradas?</strong></em></p>",
                "responses": {
                    "200": {
                        "description": "OK",
                        "examples": {
                            "application/json": [
                                {
                                    "ID_Cabana": 1,
                                    "Nombre": "Cabaña A",
                                    "Descripcion": "Para 2 personas, cómoda y cuenta con televisión",
                                    "PrecioPorNoche": 600,
                                    "Capacidad": 2,
                                    "Ubicacion": "Carretera Teotongo sin #, Villa de Tamazulapam del progreso, Oaxaca"
                                },
                                {
                                    "ID_Cabana": 2,
                                    "Nombre": "Cabaña B",
                                    "Descripcion": "Para 4 personas, cómoda y cuenta con televisión",
                                    "PrecioPorNoche": 600,
                                    "Capacidad": 2,
                                    "Ubicacion": "Carretera Teotongo sin #, Villa de Tamazulapam del progreso, Oaxaca"
                                }
                            ]
                        },
                        "schema": {
                            "$ref": "#/definitions/Cabanas"
                        }
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/cabanas/listOne/{id}": {
            "get": {
                "tags": [
                    "Cabañas"
                ],
                "summary": "Informacion asociada a la cabaña, si es que existe en el atonaltzin",
                "description": "<p>Servicio que devuelve la información detallada de la cabaña solicitada</p><p>&nbsp;</p><p><em><strong>¿Cuál es la cabaña de este ID?</strong></em></p>",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "example": [
                                    {
                                        "Nombre": "Cabaña A",
                                        "Descripcion": "Para 4 personas, cuenta con televisión, chimenea, cafetera y frigobar",
                                        "PrecioPorNoche": 1200,
                                        "Capacidad": 4,
                                        "Ubicacion": "Carretera Teotongo sin #, Villa de Tamazulapam del progreso, Oaxaca"
                                    }
                                ]
                            }
                        },
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Cabanas"
                            }
                        }
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "ID de la cabaña",
                        "schema": {
                            "type": "string",
                            "example": "1"
                        }
                    }
                ]
            }
        },
        "/api/cabanas/actualizarCabana/{id}": {
            "put": {
                "summary": "Actualizar la informaciòn de la cabaña",
                "description": "<p>Servicio que permite editar la informaciòn de la cabana de balneario atonaltzin, dado el id el mismo </p><p>&nbsp;</p>",
                "operationId": "update",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "identificador de la cabana",
                        "type": "number",
                        "default": "2"
                    },
                    {
                        "name": "Cabana",
                        "in": "body",
                        "description": "Nombre de la cabana",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/NuevaCabana"
                        }
                    }
                ],
                "tags": [
                    "Cabañas"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/cabanas/eliminarCabana/{id}": {
            "delete": {
                "tags": [
                    "Cabañas"
                ],
                "summary": "Elimina una cabaña del balneario.",
                "description": "<p>Servicio que elimina una cabaña registrada en el balneario.</p><p>&nbsp;</p><p><em><strong>¿Qué cabaña se eliminará del balneario?</strong></em></p>",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "requiered": "true",
                        "description": "Id de la cabaña.",
                        "type": "number",
                        "default": "0"
                    }
                ]
            }
        },
        "/api/reservas/addReserva/": {
            "post": {
                "summary": "Agrega una reservacion",
                "operationId": "create",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "body",
                        "description": "Reservacion agregada",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/NuevaReservacion"
                        },
                        "example": {
                            "ID_Cabana": 30,
                            "ID_Cliente": 27,
                            "FechaInicio": "2023-07-01",
                            "FechaFin": "2023-07-10"
                        }
                    }
                ],
                "tags": [
                    "Reservaciones"
                ],
                "responses": {
                    "200": {
                        "description": "Consulta con exito"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/reservas/Mostrar_reservaciones": {
            "get": {
                "tags": [
                    "Reservaciones"
                ],
                "summary": "Listado de todas las reservaciones que existen en atonaltzin.",
                "description": "<p>Servicio que devuelve la información detallada de todas las reservaciones que existen en atonaltzin.</p><p>&nbsp;</p><p><em><strong>¿Cuáles son las reservaciones que existen?</strong></em></p>",
                "responses": {
                    "200": {
                        "description": "OK",
                        "examples": {
                            "application/json": [
                                {
                                    "ID_Reservacion": 1,
                                    "ID_Cabana": 1,
                                    "ID_Cliente": 1,
                                    "FechaInicio": "2023-07-01",
                                    "FechaFin": "2023-07-10"
                                },
                                {
                                    "ID_Reservacion": 2,
                                    "ID_Cabana": 4,
                                    "ID_Cliente": 1,
                                    "FechaInicio": "2024-07-01",
                                    "FechaFin": "2024-07-10"
                                }
                            ]
                        },
                        "schema": {
                            "$ref": "#/definitions/Reservaciones"
                        }
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/reservas/showOne/{id}": {
            "get": {
                "tags": [
                    "Reservaciones"
                ],
                "summary": "Obtención de información de una reservación",
                "description": "<p>Servicio que devuelve la información detallada de una reservación</p>",
                "responses": {
                    "200": {
                        "description": "OK",
                        "examples": {
                            "application/json": [
                                {
                                    "ID_Reservacion": 1,
                                    "ID_Cabana": 1,
                                    "ID_Cliente": 1,
                                    "FechaInicio": "2023-07-01",
                                    "FechaFin": "2023-07-10"
                                }
                            ]
                        },
                        "schema": {
                            "$ref": "#/definitions/Reservacion"
                        }
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "identificador de la reservacion",
                        "type": "number",
                        "default": "1"
                    }
                ]
            }
        },
        "/api/reservas/ValidarReserva/{ID_Cabana}/{FechaInicio}/{FechaFin}": {
            "get": {
                "tags": [
                    "Reservaciones"
                ],
                "summary": "Verifica si el  la cabaña está disponible dentro del rango de fechas dado.",
                "description": "<p>Servicio que verifica la disponibilidad de una cabaña dentro de un rango de fechas dado, devuelve un resultado 1 si no se encuentra disponible y un resultado 0 si esta disponible.</p><p>&nbsp;</p><p><em><strong>¿Estará diponible la cabaña en esas fechas?</strong></em></p>",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "example": [
                                    {
                                        "resultado": 1
                                    }
                                ]
                            }
                        },
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/validarReserva"
                            }
                        }
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                },
                "parameters": [
                    {
                        "name": "ID_Cabana",
                        "in": "path",
                        "required": true,
                        "description": "Id de la cabaña.",
                        "type": "number",
                        "default": "1"
                    },
                    {
                        "name": "FechaInicio",
                        "in": "path",
                        "required": true,
                        "description": "Fecha inicial de la reservacion",
                        "schema": {
                            "type": "string",
                            "format": "date",
                            "example": "2023-07-01"
                        }
                    },
                    {
                        "name": "FechaFin",
                        "in": "path",
                        "required": true,
                        "description": "Fecha final de la reservacion",
                        "schema": {
                            "type": "string",
                            "format": "date",
                            "example": "2023-08-01"
                        }
                    }
                ]
            }
        },
        "/api/reservas/Mostrar_reservaciones_usuario/{id}": {
            "get": {
                "tags": [
                    "Reservaciones"
                ],
                "summary": "Listado de todas las reservaciones que existentes de un cliente.",
                "description": "<p>Servicio que devuelve la información detallada de todas las reservaciones de un cliente que existen en atonaltzin.</p><p>&nbsp;</p><p><em><strong>¿Cuáles son las reservaciones que existen de dicho cliente?</strong></em></p>",
                "responses": {
                    "200": {
                        "description": "OK",
                        "examples": {
                            "application/json": [
                                {
                                    "ID_Reservacion": 1,
                                    "ID_Cabana": 1,
                                    "ID_Cliente": 1,
                                    "FechaInicio": "2023-07-01",
                                    "FechaFin": "2023-07-10"
                                },
                                {
                                    "ID_Reservacion": 2,
                                    "ID_Cabana": 4,
                                    "ID_Cliente": 1,
                                    "FechaInicio": "2024-07-01",
                                    "FechaFin": "2024-07-10"
                                }
                            ]
                        },
                        "schema": {
                            "$ref": "#/definitions/Reservaciones"
                        }
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "Id del cliente",
                        "type": "number",
                        "default": "1"
                    }
                ]
            }
        },
        "/api/reservas/actualizarReservacion/{id}": {
            "put": {
                "summary": "Actualizar la información de la reservacion",
                "description": "<p>Servicio que permite editar la información de una reservacion dado el id.</p><p>&nbsp;</p>",
                "operationId": "update",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "Id de la reservación",
                        "type": "number",
                        "default": "4"
                    },
                    {
                        "name": "Reservacion",
                        "in": "body",
                        "description": "Reservación a actualizar",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/NuevaReservacion"
                        }
                    }
                ],
                "tags": [
                    "Reservaciones"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/reservas/eliminarReservacion/{id}": {
            "delete": {
                "tags": [
                    "Reservaciones"
                ],
                "summary": "Elimina una reservación del balneario.",
                "description": "<p>Servicio que elimina una reservación registrada en el balneario.</p><p>&nbsp;</p><p><em><strong>¿Qué reservación se eliminará del balneario?</strong></em></p>",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "requiered": "true",
                        "description": "Id de la reserva.",
                        "type": "number",
                        "default": "0"
                    }
                ]
            }
        },
        "/api/cobros/addCobro": {
            "post": {
                "tags": [
                    "Cobros"
                ],
                "summary": "Agrega un cobro.",
                "operationId": "create",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "cobro",
                        "in": "body",
                        "description": "<p>Información del cobro que se va a crear.</p>",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/NuevoCobro"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cobro Insertado con exito"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/cobros/showCobros": {
            "get": {
                "tags": [
                    "Cobros"
                ],
                "summary": "Listado de todos los cobros que existen en atonaltzin.",
                "description": "<p>Servicio que devuelve la información detallada de todos los cobros que existen en el balneario atonaltzin.</p><p>&nbsp;</p><p><em><strong>¿Cuáles son los cobros que existen?</strong></em></p>",
                "responses": {
                    "200": {
                        "description": "OK",
                        "examples": {
                            "application/json": [
                                {
                                    "id_Cobro": 1,
                                    "MontoCobrado": "1200"
                                },
                                {
                                    "id_Cobro": 2,
                                    "MontoCobrado": "2200"
                                }
                            ]
                        },
                        "schema": {
                            "$ref": "#/definitions/Cobros"
                        }
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/cobros/showOne/{id}": {
            "get": {
                "tags": [
                    "Cobros"
                ],
                "summary": "Muestra un cobro existente en balneario.",
                "description": "<p>Servicio que devuelve la información detallada de un cobro que existe en balneario.</p><p>&nbsp;</p><p><em><strong>¿Existe el cobro en el balneario?</strong></em></p>",
                "responses": {
                    "200": {
                        "description": "OK",
                        "examples": {
                            "application/json": [
                                {
                                    "id_Cobro": 1,
                                    "MontoCobrado": "1200"
                                }
                            ]
                        },
                        "schema": {
                            "$ref": "#/definitions/Cobro"
                        }
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "Id del cobro",
                        "type": "number",
                        "default": "0"
                    }
                ]
            }
        },
        "/api/cobros/reporteventas/{fechaInicial}/{fechaFinal}": {
            "get": {
                "tags": [
                    "Cobros"
                ],
                "summary": "Muestra un reporte de ventas en un lapso determinado del balneario.",
                "description": "<p>Servicio que devuelve un reporte de ventas de una fecha inicial a una fecha final de todas las cabañas.</p><p>&nbsp;</p><p><em><strong>¿Cuáles fueron las ventas totales en Atonaltzin?</strong></em></p>",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "example": [
                                    {
                                        "Fecha_Cobro": "2023-07-01",
                                        "Fecha_Final": "2023-08-01"
                                    }
                                ]
                            }
                        },
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Cobros"
                            }
                        }
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                },
                "parameters": [
                    {
                        "name": "fechaInicial",
                        "in": "path",
                        "required": true,
                        "description": "Fecha inicial del periodo de ventas",
                        "schema": {
                            "type": "string",
                            "format": "date",
                            "example": "2023-07-01"
                        }
                    },
                    {
                        "name": "fechaFinal",
                        "in": "path",
                        "required": true,
                        "description": "Fecha final del periodo de ventas",
                        "schema": {
                            "type": "string",
                            "format": "date",
                            "example": "2023-08-01"
                        }
                    }
                ]
            }
        },
        "/api/cobros/actualizarCobro/{id}": {
            "put": {
                "summary": "Actualizar la información del cobro",
                "description": "<p>Servicio que permite editar la información de un cobro dado el id.</p><p>&nbsp;</p>",
                "operationId": "update",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "Id del cobro",
                        "type": "number",
                        "default": 0
                    },
                    {
                        "name": "Cobro",
                        "in": "body",
                        "description": "Cobro a actualizar",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/NuevoCobro"
                        }
                    }
                ],
                "tags": [
                    "Cobros"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/cobros/eliminarCobro/{id}": {
            "delete": {
                "tags": [
                    "Cobros"
                ],
                "summary": "Elimina un cobro del balneario.",
                "description": "<p>Servicio que elimina un cobro registrado en el balneario.</p><p>&nbsp;</p><p><em><strong>¿Qué cobro se eliminará del balneario?</strong></em></p>",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "requiered": "true",
                        "description": "Id del cobro.",
                        "type": "number",
                        "default": "0"
                    }
                ]
            }
        },
        "/api/clientes/addCliente": {
            "post": {
                "tags": [
                    "Usuarios"
                ],
                "summary": "Agrega un usuario al balneario.",
                "operationId": "create",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "Usuario",
                        "in": "body",
                        "description": "<p>Información del usuario que se va a agregar.</p>",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/NuevoUsuario"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Usuario agregado"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/clientes/login": {
            "post": {
                "tags": [
                    "Usuarios"
                ],
                "summary": "Muestra el rol del usuario.",
                "operationId": "create",
                "description": "<p>Servicio que devuelve el rol del usuario.</p><p>&nbsp;</p><p><em><strong>¿Cuál es el rol del usuario</strong></em></p>",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "Email",
                        "in": "body",
                        "description": "<p>Correo electronico.</p>",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Rol encontrado"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/clientes/showOne/{id}": {
            "get": {
                "tags": [
                    "Usuarios"
                ],
                "summary": "Muestra un usuario existente en el balneario atonaltzin.",
                "description": "<p>Servicio que devuelve la información detallada de un usuario existente en el atonaltzin.</p><p>&nbsp;</p><p><em><strong>¿Existe el usuario?</strong></em></p>",
                "responses": {
                    "200": {
                        "description": "OK",
                        "examples": {
                            "application/json": [
                                {
                                    "ID_Cliente": 1,
                                    "Nombre": "Laura",
                                    "Apellido": "Gutiérrez",
                                    "Email": "laura@example.com",
                                    "Telefono": "333-444-5555"
                                }
                            ]
                        },
                        "schema": {
                            "$ref": "#/definitions/Usuario"
                        }
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "identificador del usuario",
                        "type": "number",
                        "default": "1"
                    }
                ]
            }
        },
        "/api/clientes/obtenerReservacionesPorCliente/{nombre}": {
            "get": {
                "tags": [
                    "Usuarios"
                ],
                "summary": "Muestra la informacion de reserva de un cliente.",
                "description": "<p>Servicio que devuelve la informacion de la reserva de un cliente del balneario atonaltzin.</p><p>&nbsp;</p><p><em><strong>¿Cuáles son las rerservaciones del cliente?</strong></em></p>",
                "responses": {
                    "200": {
                        "description": "OK",
                        "examples": {
                            "application/json": [
                                {
                                    "Usuario": {
                                        "Nombre": "Isabel",
                                        "Apellido": "Torres"
                                    },
                                    "Reservaciones": [
                                        {
                                            "ID_Reservacion": 3,
                                            "FechaInicio": "2023-09-10",
                                            "FechaFin": "2023-09-15"
                                        }
                                    ]
                                }
                            ]
                        },
                        "schema": {
                            "$ref": "#/definitions/ReservasClienteResponse"
                        }
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                },
                "parameters": [
                    {
                        "name": "nombre",
                        "in": "path",
                        "required": true,
                        "description": "nombre usuario",
                        "type": "string",
                        "default": "Isabel"
                    }
                ]
            }
        },
        "/api/clientes/ShowCliente": {
            "get": {
                "tags": [
                    "Usuarios"
                ],
                "summary": "Listado de todas los usuarios que existen en atonaltzin.",
                "description": "<p>Servicio que devuelve la información detallada de todos los usuarios que existen en el balneario atonaltzin.</p><p>&nbsp;</p><p><em><strong>¿Cuantos usuarios existen?</strong></em></p>",
                "responses": {
                    "200": {
                        "description": "OK",
                        "examples": {
                            "application/json": [
                                {
                                    "ID_Cliente": 1,
                                    "Nombre": "Laura",
                                    "Apellido": "Gutiérrez",
                                    "Email": "laura@example.com",
                                    "Telefono": "333-444-5555"
                                }
                            ]
                        },
                        "schema": {
                            "$ref": "#/definitions/Usuario"
                        }
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        }
    },
    "definitions": {
        "Cabana": {
            "type": "object",
            "properties": {
                " ID_Cabana": {
                    "type": "number",
                    "description": "Codigo que permite identificar la cabana",
                    "default": "1"
                },
                "nombre": {
                    "type": "string",
                    "description": "Nombre de la cabana",
                    "default": "Cabaña A"
                },
                "Descripcion": {
                    "type": "string",
                    "description": "Descripcion de la cabana",
                    "default": "Para 2 personas, cómoda y cuenta con televisión"
                },
                "PrecioPorNoche": {
                    "type": "number",
                    "description": "Precio de la cabana",
                    "default": "600"
                },
                "Capacidad": {
                    "type": "number",
                    "description": "Capacidad de cabana",
                    "default": "2"
                },
                "Ubicacion": {
                    "type": "string",
                    "description": "Descripcion de la ubicacion de la cabana",
                    "default": "Carretera Teotongo sin #, Villa de Tamazulapam del progreso, Oaxaca"
                }
            }
        },
        "Cabanas" : {
            "type" : "array",
            "items" : {
                "$ref" : "#/definitions/Cabana"
            }
        },
        "NuevaCabana": {
            "type": "object",
            "properties": {
                "nombre": {
                    "type": "string",
                    "description": "Nombre de la cabana",
                    "default": "Cabaña X"
                },
                "Descripcion": {
                    "type": "string",
                    "description": "Descripcion de la cabana",
                    "default": "Para 4 personas, cuenta con televisión, chimenea, cafetera y frigobar"
                },
                "PrecioPorNoche": {
                    "type": "number",
                    "description": "Precio de la cabana",
                    "default": "1200"
                },
                "Capacidad": {
                    "type": "number",
                    "description": "Capacidad de cabana",
                    "default": "4"
                },
                "Ubicacion": {
                    "type": "string",
                    "description": "Descripcion de la ubicacion de la cabana",
                    "default": "Carretera Teotongo sin #, Villa de Tamazulapam del progreso, Oaxaca"
                }
            }
        },
        "Reservacion": {
            "type": "object",
            "properties": {
                "ID_Reservacion": {
                    "type": "number",
                    "description": "Codigo que permite identificar la reservacion"
                },
                "ID_Cabana": {
                    "type": "number",
                    "description": "Codigo que permite identificar la cabana"
                },
                "ID_Cliente": {
                    "type": "number",
                    "description": "Codigo que permite identificar al cliente"
                },
                "FechaInicio": {
                    "type": "string",
                    "description": "Permite saber el inicio de fecha de reservacion"
                },
                "FechaFin": {
                    "type": "string",
                    "description": "Permite saber el final de la fecha de reservacion"
                }
            }
        },
        "Reservaciones" : {
            "type" : "array",
            "items" : {
                "$ref" : "#/definitions/Reservacion"
            }
        },
        "NuevaReservacion": {
            "type": "object",
            "properties": {
                "ID_Cabana": {
                    "type": "number",
                    "description": "Codigo que permite identificar la cabana",
                    "default": "30"
                },
                "ID_Cliente": {
                    "type": "number",
                    "description": "Codigo que permite identificar al cliente",
                    "default": "27"
                },
                "FechaInicio": {
                    "type": "string",
                    "description": "Permite saber el inicio de fecha de reservacion",
                    "default": "2023-07-01"
                },
                "FechaFin": {
                    "type": "string",
                    "description": "Permite saber el final de la fecha de reservacion",
                    "default": "2023-07-10"
                }
            }
        },
        "Cobro": {
            "type": "object",
            "properties": {
                "IdCobro": {
                    "type": "number",
                    "description": "Codigo que permite identificar el cobro"
                },
                "IdReservacion": {
                    "type": "number",
                    "description": "Codigo que permite identificar la reservacion"
                },
                "MontoCobrado": {
                    "type": "number",
                    "description": "Codigo que permite identificar la reservacion"
                },
                "Fecha_Cobro": {
                    "type": "string",
                    "format": "date",
                    "example": "2024-02-10",
                    "description": "Permite saber la fecha del cobro"
                },
                "Estado": {
                    "type": "string",
                    "description": "Permite saber el estado del cobro"
                }
            }
        },
        "Cobros" : {
            "type" : "array",
            "items" : {
                "$ref" : "#/definitions/Cobros"
            }
        },
        "NuevoCobro": {
            "type": "object",
            "properties": {
                "IdReservacion": {
                    "type": "number",
                    "description": "Codigo que permite identificar la reservacion"
                },
                "MontoCobrado": {
                    "type": "number",
                    "description": "Codigo que permite identificar la reservacion"
                },
                "Fecha_Cobro": {
                    "type": "string",
                    "description": "Fecha para saber cuando de hizo el cobro"
                },
                "Estado": {
                    "type": "string",
                    "description": "Estado del cobro"
                }
            }
        },
        "ReservasClienteResponse": {
            "type": "object",
            "properties": {
                "Usuario": {
                    "$ref": "#/definitions/Usuario"
                },
                "Reservaciones": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Reservaciones"
                    }
                }
            }
        },
        "Usuario": {
            "type": "object",
            "properties": {
                "ID_Cliente": {
                    "type": "number",
                    "description": "Identificador del usuario"
                },
                "Nombre": {
                    "type": "string",
                    "description": "Nombre del usuario"
                },
                "Apellido": {
                    "type": "string",
                    "description": "Apellido del usuario"
                },
                "Email": {
                    "type": "string",
                    "description": "Email del usuario"
                },
                "Telefono": {
                    "type": "number",
                    "description": "Telefono del usuario"
                },
                "password1": {
                    "type": "string",
                    "description": "Contraseña del usuario"
                },
                "Tipo": {
                    "type": "string",
                    "description": "Tipo de usuario"
                }
            }
        },
        "Usuarios" : {
            "type" : "array",
            "items" : {
                "$ref" : "#/definitions/Usuario"
            }
        },
        "NuevoUsuario": {
            "type": "object",
            "properties": {
                "Nombre": {
                    "type": "string",
                    "description": "Nombre del usuario"
                },
                "Apellido": {
                    "type": "string",
                    "description": "Apellido del usuario"
                },
                "Email": {
                    "type": "string",
                    "description": "Email del usuario"
                },
                "Telefono": {
                    "type": "number",
                    "description": "Telefono del usuario"
                },
                "password1": {
                    "type": "string",
                    "description": "Contraseña del usuario"
                },
                "Tipo": {
                    "type": "string",
                    "description": "Tipo de usuario"
                }
            }
        },
        "Login": {
            "type": "object",
            "properties": {
                "Email": {
                    "type": "string",
                    "description": "Email del usuario"
                },
                "password1": {
                    "type": "string",
                    "description": "Contraseña del usuario"
                }
            }
        }
    }
}